[build]
  command = "cd client && npm cache clean --force && (npm ci --legacy-peer-deps --force || npm install --legacy-peer-deps --force || npm install --force) && npm run build && cp -r ../assets dist/"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NPM_CONFIG_FORCE = "true"
  NPM_CONFIG_AUDIT = "false"

[[redirects]]
  from = "/api/*"
  to = "https://nayrana-handicrafts-api.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 