[build]
  command = "cd client && npm install --legacy-peer-deps && npm run build && cp -r ../assets dist/"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://nayrana-handicrafts-api.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 